name: clang

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: "Full LLVM version (XX.Y.Z)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      major: ${{ steps.get_major.outputs.major }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./clang
          push: true
          build-args: LLVM_VERSION=${{ inputs.llvm_version }}
          tags: ghcr.io/k3dw/clang:${{ inputs.llvm_version }}

      - name: Get major version
        id: get_major
        run: |
          echo "major=$(echo '${{ inputs.llvm_version }}' | cut -d. -f1)" >> $GITHUB_OUTPUT

  tag:
    needs: build
    uses: ./.github/workflows/refresh-latest.yml
    permissions:
      contents: read
      packages: write
    with:
      image_name: clang
      prefix: ${{ needs.build.outputs.major }}
